<?='<?'?>
use oxygen\common\form_collection\FormCollection;
# WARNING !!!
# This class has been generated by Oxygen.
# Any changes here will be overwritten on the next genertion.

<?$m = $this->model?>
class <?=$m['classNameCollection']['form']?>_ extends FormCollection {
    public function configure($x) {
        $x['<?=$m['pattern']?>']-><?=$m['className']['form']?>($this->model);
    }
}

<?='?>'?>