<?='<?'?>

# WARNING !!!
# This class has been generated by Oxygen.
# Any changes here will be overwritten on the next genertion.

<?$m = $this->model?>
class <?=$m['classNameCollection']['form']?>_ extends Oxygen_Common_FormCollection {
    public function configure($x) {
        $x['<?=$m['pattern']?>']-><?=$m['className']['form']?>($this->model);
    }
}

<?='?>'?>