<?='<?'?>

# WARNING !!!
# This class has been generated by Oxygen.
# Any changes here will be overwritten on the next genertion.

<?$m = $this->model?>
class <?=$m['className']['form']?>_ extends <?=$this->parent->model['form']?> {
    public function configure($x) {
<?foreach($m['fields'] as $fieldName => $fieldDef):?>
<?switch($fieldDef['type']): case 'object': case 'collection': case 'cross' :?>
      <?try{?>
       $x['<?=$fieldName?>']-><?=$fieldDef['class']['form']?>($this->model-><?=$this[$fieldName]->model->nameFor('get')?>());
      <?}catch(Exception $e){?>
        TEST
      <?}?>
<?endswitch?>
<?endforeach?>
    }
}

<?='?>'?>