<?='<?'?>
use oxygen\sql\data_set\DataSet;
# WARNING !!!
# This class has been generated by Oxygen.
# Any changes here will be overwritten on the next genertion.

<?$m = $this->model?>
class <?=$m['classNameCollection']['model']?>_ extends DataSet {

}

<?='?>'?>