<?='<?'?>

# WARNING !!!
# This class has been generated by Oxygen.
# Any changes here will be overwritten on the next genertion.

<?$m = $this->model?>
class <?=$m['classNameCollection']['model']?>_ extends Oxygen_Sql_DataSet {

}

<?='?>'?>