<?='<?'?>

# WARNING !!!
# This class has been generated by Oxygen.
# Any changes here will be overwritten on the next genertion.

<?$m = $this->model?>
class <?=$m['classNameCollection']['page']?>_ extends Oxygen_Common_PageCollection {
    public function configure($x) {
        $x['<?=$m['pattern']?>']-><?=$m['className']['page']?>($this->model);
    }
}

<?='?>'?>