<? return array('AD' => 'Andorra', 'AE' => 'United Arab Emirates', 'AF' => 'Afghanistan', 'AG' => 'Antigua and Barbuda', 'AL' => 'Albania'
  , 'AM' => 'Armenia', 'AN' => 'Netherlands Antilles', 'AO' => 'Angola', 'AR' => 'Argentina', 'AT' => 'Austria'
  , 'AU' => 'Australia', 'AW' => 'Aruba', 'AZ' => 'Azerbaijan', 'BA' => 'Bosnia and Herzegowina', 'BB' => 'Barbados'
  , 'BD' => 'Bangladesh', 'BE' => 'Belgium', 'BF' => 'Burkina Faso', 'BG' => 'Bulgaria', 'BH' => 'Bahrain'
  , 'BJ' => 'Benin', 'BM' => 'Bermuda', 'BN' => 'Brunei Darussalam', 'BO' => 'Bolivia', 'BR' => 'Brazil'
  , 'BS' => 'Bahamas', 'BT' => 'Bhutan', 'BW' => 'Botswana', 'BY' => 'Belarus', 'BZ' => 'Belize'
  , 'CA' => 'Canada', 'CD' => 'Congo The Democratic Republic of The', 'CF' => 'Central African Republic', 'CG' => 'Congo', 'CH' => 'Switzerland'
  , 'CI' => 'Cote D\'ivoire', 'CL' => 'Chile', 'CM' => 'Cameroon', 'CN' => 'China', 'CO' => 'Colombia'
  , 'CR' => 'Costa Rica', 'CU' => 'Cuba', 'CV' => 'Cape Verde', 'CY' => 'Cyprus', 'CZ' => 'Czech Republic'
  , 'DE' => 'Germany', 'DJ' => 'Djibouti', 'DK' => 'Denmark', 'DO' => 'Dominican Republic', 'DZ' => 'Algeria'
  , 'EC' => 'Ecuador', 'EE' => 'Estonia', 'EG' => 'Egypt', 'ES' => 'Spain', 'EU' => 'European Union'
  , 'FI' => 'Finland', 'FJ' => 'Fiji', 'FM' => 'Micronesia Federated States of', 'FO' => 'Faroe Islands', 'FR' => 'France'
  , 'GA' => 'Gabon', 'GB' => 'United Kingdom', 'GD' => 'Grenada', 'GE' => 'Georgia', 'GG' => 'Guernsey'
  , 'GH' => 'Ghana', 'GI' => 'Gibraltar', 'GL' => 'Greenland', 'GM' => 'Gambia', 'GN' => 'Guinea'
  , 'GQ' => 'Equatorial Guinea', 'GR' => 'Greece', 'GT' => 'Guatemala', 'GU' => 'Guam', 'GY' => 'Guyana'
  , 'HK' => 'Hong Kong', 'HN' => 'Honduras', 'HR' => 'Croatia (LOCAL Name: Hrvatska)', 'HT' => 'Haiti', 'HU' => 'Hungary'
  , 'ID' => 'Indonesia', 'IE' => 'Ireland', 'IL' => 'Israel', 'IM' => 'Isle of Man', 'IN' => 'India'
  , 'IQ' => 'Iraq', 'IR' => 'Iran (ISLAMIC Republic Of)', 'IS' => 'Iceland', 'IT' => 'Italy', 'JE' => 'Jersey'
  , 'JM' => 'Jamaica', 'JO' => 'Jordan', 'JP' => 'Japan', 'KE' => 'Kenya', 'KG' => 'Kyrgyzstan'
  , 'KH' => 'Cambodia', 'KP' => 'Korea Democratic People\'s Republic of', 'KR' => 'Korea Republic of', 'KW' => 'Kuwait', 'KY' => 'Cayman Islands'
  , 'KZ' => 'Kazakhstan', 'LA' => 'Lao People\'s Democratic Republic', 'LB' => 'Lebanon', 'LI' => 'Liechtenstein', 'LK' => 'Sri Lanka'
  , 'LR' => 'Liberia', 'LS' => 'Lesotho', 'LT' => 'Lithuania', 'LU' => 'Luxembourg', 'LV' => 'Latvia'
  , 'LY' => 'Libyan Arab Jamahiriya', 'MA' => 'Morocco', 'MC' => 'Monaco', 'MD' => 'Moldova Republic of', 'ME' => 'Montenegro'
  , 'MF' => 'Saint Martin', 'MG' => 'Madagascar', 'MH' => 'Marshall Islands', 'MK' => 'Macedonia', 'ML' => 'Mali'
  , 'MM' => 'Myanmar', 'MN' => 'Mongolia', 'MO' => 'Macau', 'MR' => 'Mauritania', 'MT' => 'Malta'
  , 'MU' => 'Mauritius', 'MV' => 'Maldives', 'MW' => 'Malawi', 'MX' => 'Mexico', 'MY' => 'Malaysia'
  , 'MZ' => 'Mozambique', 'NA' => 'Namibia', 'NC' => 'New Caledonia', 'NE' => 'Niger', 'NG' => 'Nigeria'
  , 'NI' => 'Nicaragua', 'NL' => 'Netherlands', 'NO' => 'Norway', 'NP' => 'Nepal', 'NU' => 'Niue'
  , 'NZ' => 'New Zealand', 'OM' => 'Oman', 'PA' => 'Panama', 'PE' => 'Peru', 'PF' => 'French Polynesia'
  , 'PG' => 'Papua New Guinea', 'PH' => 'Philippines', 'PK' => 'Pakistan', 'PL' => 'Poland', 'PM' => 'St. Pierre and Miquelon'
  , 'PR' => 'Puerto Rico', 'PS' => 'Palestinian Territory Occupied', 'PT' => 'Portugal', 'PY' => 'Paraguay', 'QA' => 'Qatar'
  , 'RE' => 'Reunion', 'RO' => 'Romania', 'RS' => 'Serbia', 'RU' => 'Russian Federation', 'RW' => 'Rwanda'
  , 'SA' => 'Saudi Arabia', 'SC' => 'Seychelles', 'SD' => 'Sudan', 'SE' => 'Sweden', 'SG' => 'Singapore'
  , 'SI' => 'Slovenia', 'SK' => 'Slovakia (SLOVAK Republic)', 'SL' => 'Sierra Leone', 'SM' => 'San Marino', 'SN' => 'Senegal'
  , 'SO' => 'Somalia', 'SR' => 'Suriname', 'SV' => 'El Salvador', 'SY' => 'Syrian Arab Republic', 'SZ' => 'Swaziland'
  , 'TC' => 'Turks and Caicos Islands', 'TD' => 'Chad', 'TG' => 'Togo', 'TH' => 'Thailand', 'TJ' => 'Tajikistan'
  , 'TK' => 'Tokelau', 'TL' => 'Timor-leste', 'TM' => 'Turkmenistan', 'TN' => 'Tunisia', 'TO' => 'Tonga'
  , 'TR' => 'Turkey', 'TT' => 'Trinidad and Tobago', 'TW' => 'Taiwan; Republic of China (ROC)', 'TZ' => 'Tanzania United Republic of', 'UA' => 'Ukraine'
  , 'UG' => 'Uganda', 'US' => 'United States', 'UY' => 'Uruguay', 'UZ' => 'Uzbekistan', 'VC' => 'Saint Vincent and The Grenadines'
  , 'VE' => 'Venezuela', 'VG' => 'Virgin Islands (BRITISH)', 'VI' => 'Virgin Islands (U.S.)', 'VN' => 'Viet Nam', 'VU' => 'Vanuatu'
  , 'WF' => 'Wallis and Futuna Islands', 'WS' => 'Samoa', 'YE' => 'Yemen', 'ZA' => 'South Africa', 'ZM' => 'Zambia'
  , 'ZW' => 'Zimbabwe', 'ZZ' => 'Reserved');?>